### ISSUE TITLE
bucket.disconnect is not working properly

### ISSUE THREAD

**Issue by MerzDaniel** [actano/rplan-couchbase#1]
It is not possible to properly close the connection to a bucket. 

```
import { bucket } from '@rplan/couchbase'
import config from '@rplan/config'
async fun() => {
  config.set({ couchbase: { host: 'VALID_HOST' } }
  await bucket().disconnect()  // seems to call process.exit()

  config.set({ couchbase: { host: 'NON_VALID_HOST' } }
  await bucket().disconnect()  // Nether returns.
}
```

**Comment by pithu** [comment]
Right, looks like it is promisified by accident. it has no callback, i will fix it.

work arround is to call it without await. like this works for me https://github.com/actano/rplan-planning-objects/blob/2446a675f7a384bfd74ed2dfd40b6c042ab954d2/src/playground/traverse-scripts/index.js#L32

**Comment by pithu** [comment]
Disconnect is not async, i updated readme.
